app/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView

from movingbox.admin import admin_site
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('movingbox/', include('movingbox.urls')),
    path('movingbox/admin/', admin_site.urls, name='app_admin'),
    path('movingbox/qr_code/', include(qr_code_urls, namespace="qr_code")),
    path('admin/', admin.site.urls),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='movingbox/static/favicon.ico')),
]

movingbox/urls.py
from django.urls import path, include

from movingbox import views

app_name = 'movingbox'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('restricted', views.get_restricted, name='restricted'),
    path('account/', include([
        path('<int:pk>/', views.AccountView.as_view(), name='account'),
        path('<int:pk>/update_password', views.update_account_password, name='update_password'),
        path('login', views.get_login, name='login'),
        path('submit_login', views.post_login, name='post_login'),
        path('logout', views.get_logout, name='logout'),
    ])),
    path('rooms/', include([
        path('', views.RoomsView.as_view(), name='get_rooms'),
        path('<int:pk>/', views.RoomView.as_view(), name='get_room'),
        path('add/', views.AddRoomView.as_view(), name='add_room'),
        path('<int:pk>/update/', views.UpdateRoomView.as_view(), name='update_room'),
        path('<int:pk>/delete/', views.DeleteRoomView.as_view(), name='delete_room'),
        path('<int:room>/box/<int:pk>/', views.BoxView.as_view(), name='get_room_box'),
        path('<int:room>/box/<int:room_number>/item/<int:pk>/', views.ItemView.as_view(), name='get_room_box_item'),
        path('<int:room>/furniture/<int:pk>/', views.FurnitureView.as_view(), name='get_room_furniture'),
    ])),
    path('boxes/', include([
        path('', views.BoxesView.as_view(), name='get_boxes'),
        path('<int:pk>/', views.BoxView.as_view(), name='get_box'),
        path('add/', views.AddBoxView.as_view(), name='add_box'),
        path('add/<int:room>/', views.AddBoxView.as_view(), name='add_box_to_room'),
        path('<int:pk>/update/', views.UpdateBoxView.as_view(), name='update_box'),
        path('<int:pk>/delete/', views.DeleteBoxView.as_view(), name='delete_box'),
        path('<int:box_number>/item/<int:pk>/', views.ItemView.as_view(), name='get_box_item'),
    ])),
    path('items/', include([
        path('', views.all_items, name='get_items'),
        path('<int:pk>/', views.ItemView.as_view(), name='get_item'),
        path('add/', views.AddItemView.as_view(), name='add_item'),
        path('add/<int:box>/', views.AddItemView.as_view(), name='add_item_to_box'),
        path('<int:pk>/update/', views.UpdateItemView.as_view(), name='update_item'),
        path('<int:pk>/delete/', views.DeleteItemView.as_view(), name='delete_item'),
        path('search', views.post_search_items, name='post_search_items'),
        path('result', views.search_items, name='search_items'),
    ])),
    path('furnitures/', include([
        path('', views.FurnituresView.as_view(), name='get_furnitures'),
        path('<int:pk>/', views.FurnitureView.as_view(), name='get_furniture'),
        path('add/', views.AddFurnitureView.as_view(), name='add_furniture'),
        path('add/<int:room>/', views.AddFurnitureView.as_view(), name='add_furniture_to_room'),
        path('<int:pk>/update/', views.UpdateFurnitureView.as_view(), name='update_furniture'),
        path('<int:pk>/delete/', views.DeleteFurnitureView.as_view(), name='delete_furniture'),
    ])),
    path('users/', include([
        path('', views.UsersView.as_view(), name='get_users'),
        path('<int:pk>/', views.UserView.as_view(), name='get_user'),
        path('add/', views.AddUserView.as_view(), name='add_user'),
        path('<int:pk>/update/', views.UpdateUserView.as_view(), name='update_user'),
        path('<int:pk>/delete/', views.DeleteUserView.as_view(), name='delete_user'),
        path('<int:pk>/password/', views.update_user_password, name='password_user'),
    ])),
    path('printer/', include([
        path('room/<int:pk>/', views.RoomPrintView.as_view(), name='print_room'),
        path('box/<int:pk>/', views.BoxPrintView.as_view(), name='print_box'),
        path('furniture/<int:pk>/', views.FurniturePrintView.as_view(), name='print_furniture'),
    ])),
]

movingbox/views/forms.py
from typing import Dict

from django.contrib.auth.forms import UserCreationForm, UsernameField, UserChangeForm
from django.contrib.auth.models import Group
from django.db.models import Model
from django.forms import Field

from movingbox.models import AppUser


class AppUserChangeForm(UserChangeForm):
    class Meta:
        model: Model = AppUser
        fields: Field = ['username', 'first_name', 'last_name', 'email']
        field_classes: Dict[str, Field] = {'username': UsernameField}


class AppUserCreationForm(UserCreationForm):
    class Meta:
        model: Model = AppUser
        fields: Field = ["username"]
        field_classes: Dict[str, Field] = {'username': UsernameField}

    def save(self, commit=True):
        user: AppUser = super(AppUserCreationForm, self).save(commit=True)
        user.groups.add(Group.objects.get(name='Mover'))
        if commit:
            user.save()
        return user

movingbox/views/decorators.py
from functools import wraps
from typing import Callable
from urllib.parse import urlparse

from django.conf import settings
from django.shortcuts import resolve_url

from movingbox.models import AppUser


def user_passes_test(test_func: Callable[[AppUser], bool], login_url: str = None, restricted_url: str = None):
    """
    Decorator for views that checks that the user passes the given test,
    redirecting to the log-in page if necessary. The test should be a callable
    that takes the user object and returns True if the user passes.
    """

    def decorator(view_func: Callable):
        @wraps(view_func)
        def _wrapped_view(request, *args, **kwargs):
            if test_func(request.user):
                return view_func(request, *args, **kwargs)
            path = request.build_absolute_uri()
            if request.user.is_authenticated:
                resolved_login_url = resolve_url(restricted_url or settings.RESTRICTED_URL)
            else:
                resolved_login_url = resolve_url(login_url or settings.LOGIN_URL)
            # If the login url is the same scheme and net location then just
            # use the path as the "next" url.
            login_scheme, login_netloc = urlparse(resolved_login_url)[:2]
            current_scheme, current_netloc = urlparse(path)[:2]
            if ((not login_scheme or login_scheme == current_scheme) and
                    (not login_netloc or login_netloc == current_netloc)):
                path = request.get_full_path()
            from django.contrib.auth.views import redirect_to_login
            return redirect_to_login(path, resolved_login_url)

        return _wrapped_view

    return decorator


def mover_required(function: Callable[[AppUser], bool] = None, login_url: str = None, restricted_url: str = None):
    """
    Decorator for views that checks that the user is mover in, redirecting
    to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_mover(),
        login_url=login_url,
        restricted_url=restricted_url
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


def resident_required(function: Callable[[AppUser], bool] = None, login_url: str = None, restricted_url: str = None):
    """
    Decorator for views that checks that the user is resident in, redirecting
    to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_resident(),
        login_url=login_url,
        restricted_url=restricted_url
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


def admin_required(function: Callable[[AppUser], bool] = None, login_url: str = None, restricted_url: str = None):
    """
    Decorator for views that checks that the user is admin in, redirecting
    to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_admin(),
        login_url=login_url,
        restricted_url=restricted_url
    )
    if function:
        return actual_decorator(function)
    return actual_decorator

movingbox/views/generic_views.py
from typing import List, Any, Dict

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Model
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.views.generic import UpdateView, CreateView, DeleteView, DetailView, ListView

from movingbox.views.mixins import ResidentRequiredMixin, MoverRequiredMixin
from movingbox.views.utils import __get__title__, get_login_url, get_previous_url, update_per_page_session_cookie


class ElementView(MoverRequiredMixin, DetailView):
    model: Model = None
    login_url: str = get_login_url()
    redirect_field_name = 'target'
    template_name: str = None
    allow_empty: bool = False
    view_title: str = 'View Element'

    def get_view_title(self) -> str:
        return self.view_title

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super(ElementView, self).get_context_data(**kwargs)
        context.update({
            'title': __get__title__(self.get_view_title()),
        })
        return context


class ElementsListView(MoverRequiredMixin, ListView):
    model: Model = None
    login_url: str = get_login_url()
    redirect_field_name = 'target'
    template_name: str = None
    view_title: str = 'View Elements List'
    per_page_attr: str = 'per_page'
    page_attr: str = 'page'
    cookie_per_page: str = 'objects_per_page'
    is_paginated: bool = False

    def get_view_title(self) -> str:
        return self.view_title

    def get_paginate_by(self, queryset) -> int:
        if self.is_paginated:
            return update_per_page_session_cookie(self.request, self.per_page_attr, self.cookie_per_page)
        else:
            return None

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super(ElementsListView, self).get_context_data(**kwargs)
        context.update({
            'is_paginated': False,
            'title': __get__title__(self.get_view_title()),
        })
        if self.is_paginated:
            context.update({
                'is_paginated': True,
                'paginator_page': context['page_obj'],
                'per_page_attr': self.per_page_attr,
                'page_attr': self.page_attr,
            })
        return context


class EditElementView(ResidentRequiredMixin, SuccessMessageMixin):
    model: Model = None
    fields: List[str] = []
    template_name: str = 'edit_element.html'
    login_url: str = get_login_url()
    redirect_field_name = 'target'
    allow_empty: bool = False
    element_name: str = 'Element'
    redirect_url: str = 'movingbox:index'
    cancel_url: str = 'movingbox:index'
    form_title: str = 'Edit an Element'
    submit_button: str = 'Save Element'
    submit_icon: str = 'save'
    submit_color: str = 'info'
    back_to_previous: bool = True

    def get_redirect_args(self) -> List[Any]:
        return []

    def get_cancel_args(self) -> List[Any]:
        return []

    def get_success_message(self, _=None) -> str:
        return '%s successfully edited!' % self.element_name

    def resolve_redirect_url(self) -> str:
        return reverse_lazy(self.redirect_url, args=self.get_redirect_args())

    def resolve_cancel_url(self) -> str:
        return reverse_lazy(self.cancel_url, args=self.get_cancel_args())

    def get_success_url(self) -> str:
        return self.resolve_redirect_url()

    def get_cancel_url(self) -> str:
        return self.resolve_cancel_url()

    def get_previous_url(self) -> str:
        return get_previous_url(self.request, self.get_cancel_url())

    def get_form_title(self) -> str:
        return self.form_title

    def get_context(self) -> Dict[str, Any]:
        cancel_url: str = self.get_previous_url()
        return {
            'title': __get__title__(self.form_title),
            'cancel_url': cancel_url,
            'form_title': format_html(self.get_form_title()),
            'submit_button': self.submit_button,
            'submit_icon': self.submit_icon,
            'submit_color': self.submit_color,
        }


class AddElementView(EditElementView, CreateView):
    form_title: str = 'Add an Element'
    submit_button: str = 'Create Element'
    submit_icon: str = 'plus-square'
    submit_color: str = 'success'
    redirect_url: str = 'movingbox:index'
    cancel_url: str = 'movingbox:index'

    def get_success_message(self, _=None) -> str:
        return '%s successfully created!' % self.element_name

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super(AddElementView, self).get_context_data(**kwargs)
        context.update({
            **super(AddElementView, self).get_context(),
            'element_form': context['form'],
        })
        return context

    def get_initial(self) -> Dict[str, Any]:
        initial = super(AddElementView, self).get_initial()
        initial = {**initial, **self.kwargs}
        return initial


class UpdateElementView(EditElementView, UpdateView):
    form_title: str = 'Update an Element'
    submit_button: str = 'Save Element'
    submit_color: str = 'primary'
    extra_button: Dict[str, str] = None

    def get_extra_button(self) -> Dict[str, str]:
        return self.extra_button

    def get_success_message(self, _=None) -> str:
        return '%s successfully updated!' % self.element_name

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super(UpdateElementView, self).get_context_data(**kwargs)
        context.update({
            **super(UpdateElementView, self).get_context(),
            'element_form': context['form'],
            'extra_button': self.get_extra_button(),
        })
        return context


class DeleteElementView(EditElementView, DeleteView):
    form_title: str = 'Delete an Element'
    submit_button: str = 'Delete Element'
    submit_icon: str = 'trash'
    submit_color: str = 'danger'

    def get_confirmation_msg(self) -> str:
        return format_html('Are you sure you want to delete the <i>%s</i> "<b>%s</b>"?' %
                           (self.element_name, str(self.object)))

    def get_success_message(self, _=None) -> str:
        return '%s successfully removed!' % self.element_name

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super(DeleteElementView, self).get_context_data(**kwargs)
        context.update({
            **super(DeleteElementView, self).get_context(),
            'confirmation_msg': self.get_confirmation_msg(),
            'delete_element': True,
        })
        return context

    def delete(self, request, *args, **kwargs) -> HttpResponseRedirect:
        response: HttpResponseRedirect = super().delete(self, request, args, kwargs)
        messages.success(self.request, self.get_success_message())
        return response

movingbox/views/mixins.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied

from movingbox.views.utils import get_restricted_url


class MoverRequiredMixin(LoginRequiredMixin):
    """Verify that the current user is mover."""
    restricted_url: str = get_restricted_url()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_mover():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def get_restricted_url(self) -> str:
        return self.restricted_url or self.get_login_url()

    def handle_no_permission(self):
        if self.raise_exception:
            raise PermissionDenied(self.get_permission_denied_message())
        redirect_url: str
        if self.request.user.is_authenticated:
            redirect_url = self.get_restricted_url()
        else:
            redirect_url = self.get_login_url()
        return redirect_to_login(self.request.get_full_path(), redirect_url, self.get_redirect_field_name())


class ResidentRequiredMixin(MoverRequiredMixin):
    """Verify that the current user is resident."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_resident():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class AdminRequiredMixin(ResidentRequiredMixin):
    """Verify that the current user is admin."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_admin():
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

movingbox/templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load fontawesome %}
{% load filters %}
{% load tags %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{{title}}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <link rel="icon" href="{% static 'favicon.ico' %}" >
  {% block header %}
  {% endblock %}
  {% fontawesome_stylesheet %}
</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movingbox:index' %}">Moving Box</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movingbox:get_rooms' %}">Rooms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movingbox:get_boxes' %}">Boxes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movingbox:get_furnitures' %}">Furnitures</a>
      </li>
      {% if request.user.is_resident %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movingbox:get_items' %}">Items</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movingbox:get_users' %}">Users</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}
      {% if request.user.is_resident %}
      <li class="nav-item dropdown d-xs-block d-sm-none">
        <a class="dropdown-toggle nav-link my-2" href="#" id="navbarDropdown" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Search
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
          {% with 'search-items' as input_id %}
          {% with 'w-auto mr-auto ml-auto' as input_class %}
          {% include 'search_items_form.html' %}
          {% endwith %}
          {% endwith %}
        </div>
      </li>
      <li class="nav-item dropdown d-none d-sm-block">
        {% with 'search-items-inline' as input_id %}
        {% with 'my-2 my-md-0 mx-2' as form_class %}
        {% with 'mr-sm-2' as input_class %}
        {% with 'my-2 my-sm-0' as button_class %}
        {% include 'search_items_form.html' %}
        {% endwith %}
        {% endwith %}
        {% endwith %}
        {% endwith %}
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="dropdown-toggle text-success nav-link" href="#" id="userDropdown" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <b>Account</b>
        </a>
        <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="userDropdown">
          <h6 class="dropdown-header text-light">Connected as
            <b>{{ request.user.first_name|default:request.user }}</b>
            ({{ request.user }})
          </h6>
          <a class="dropdown-item text-light bg-dark" href="{% url 'movingbox:account' request.user.id %}">
            {% fontawesome_icon 'edit' %} Account settings
          </a>
          {% if request.user.is_authenticated and request.user.is_superuser %}
          <a class="dropdown-item text-light bg-dark" href="{% url 'app_admin:index' %}">
            {% fontawesome_icon 'cogs' %} Admin Site
          </a>
          {% endif %}
          <div class="dropdown-divider text-light bg-dark"></div>
          <a class="dropdown-item text-danger bg-dark" href="{% url 'movingbox:logout' %}">
            <b>{% fontawesome_icon 'sign-out' %} Logout</b>
          </a>
        </div>
      </li>
      {% else %}
      <li>
        <a class="btn btn-primary" href="{% url 'movingbox:login' %}">
          {% fontawesome_icon 'user' %} <b>Login</b>
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
<div>
  {% bootstrap_messages %}
</div>
{% block sitemap %}
{% include 'sitemap.html' %}
{% endblock %}
<div class="container-fluid">
  {% block content %}
  {% endblock %}
</div>
<nav class="navbar d-none d-sm-block fixed-bottom navbar-expand navbar-dark bg-dark py-0 my-0">
  <ul class="navbar-nav py-0 my-0">
    <li class="nav-item mr-auto">
      <span class="nav-link">{{ app_settings|get_item:'bottom_text' }}</span>
    </li>
    <li class="nav-item ml-auto dropup">
      <a class="dropdown-toggle nav-link" href="#" id="repoDropup" role="button"
         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Moving Box
      </a>
      <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="repoDropup">
        <h6 class="dropdown-header text-light">Developed by
          <b><a class="text-warning" target=_blank" href="https://gitlab.com/nemolovich">
            {% fontawesome_icon 'gitlab' %} Nemolovich
          </a></b>
        </h6>
        <a class="nav-link" target=_blank" href="https://gitlab.com/nemolovich/moving-box">
          {% fontawesome_icon 'code' %} Moving Box - Gitlab repository
        </a>
        <a class="nav-link" target=_blank" href="https://hub.docker.com/r/nemolovich/movingbox">
          {% fontawesome_icon 'cube' %} Moving Box - Docker Hub
        </a>
      </div>
    </li>
  </ul>
</nav>
</body>
</html>

movingbox/templates/edit_element.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load fontawesome %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ form_title }}</h5>
    {% if delete_element %}
    <h6 class="card-title">{{ confirmation_msg }}</h6>
    {% endif %}
    <p class="card-text">
    <form class="needs-validation" action="" method="post">
      {% csrf_token %}
      {% if not delete_element %}
      {% bootstrap_form element_form layout="horizontal" size="small" label_class="form-label col-md-3" %}
      {% endif %}
      <div class="row">
        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-7 col-xs-12">
          {% buttons %}
          <button class="form-button btn btn-{{ submit_color }} w-100" type="submit">
            {% fontawesome_icon submit_icon %} {{ submit_button }}
          </button>
          {% endbuttons %}
        </div>
        {% if extra_button %}
          <div class="col-xl-2 col-lg-3 col-md-4 col-sm-7 col-xs-12">
            {% buttons %}
            <a class="form-button btn btn-{{ extra_button.color }} w-100" href="{{ extra_button.url }}">
              {% fontawesome_icon extra_button.icon %} {{ extra_button.text }}
            </a>
            {% endbuttons %}
          </div>
        {% endif %}
        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-7 col-xs-12">
          {% buttons %}
          <a class="form-button btn btn-secondary w-100" href="{{ cancel_url }}">
            {% fontawesome_icon 'times-circle' %} Cancel
          </a>
          {% endbuttons %}
        </div>
      </div>
    </form>
    </p>
  </div>
</div>
{% endblock %}}

movingbox/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}

{% block content %}
<div class="card">
  <div class="img-wrapper"
       alt-msg="Image (APP_HOME_IMAGE)"
       style="background-image: url({% static home_image %});">
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ home_title }}</h5>
    <p class="card-text">{{ home_message }}</p>
    {% if not request.user.is_authenticated %}
    <p>Please login to see the content.</p>
    <a href="{% url 'movingbox:login' %}" class="btn btn-primary col-xs-12 col-sm-auto">{% fontawesome_icon 'user' %}
      Login
    </a>
    {% endif %}
  </div>
</div>
{% endblock %}

movingbox/templates/object_paginator.html
{% if paginator_page.has_other_pages %}
{% with 'd-inline-flex d-sm-none' as display_class %}
{% with 'pl-2 pr-2' as btn_class %}
{% with 'pl-1 pr-1' as arrow_class %}
{% with 'pl-0 pr-0' as more_class %}
{% include 'paginator_nav.html' with pages_arround=2 %}
{% endwith %}
{% endwith %}
{% endwith %}
{% endwith %}
{% with 'd-none d-sm-inline-flex d-md-none' as display_class %}
{% with 'pl-2 pr-2' as arrow_class %}
{% with 'pl-1 pr-1' as more_class %}
{% include 'paginator_nav.html' with pages_arround=4 %}
{% endwith %}
{% endwith %}
{% endwith %}
{% with 'd-none d-md-inline-flex' as display_class %}
{% include 'paginator_nav.html' with pages_arround=6 %}
{% endwith %}
{% endif %}

movingbox/templates/object_table.html
<table class="table table-striped table-bordered">
  {% if display_header %}
  <thead>
  {% if is_paginated %}
  {% include 'paginator_header.html' with nb_cols=2 %}
  {% endif %}
  <tr>
    <th scope="col">{{ object_type }} Name</th>
    {% if display_room %}
    <th scope="col">Room Name</th>
    {% endif %}
  </tr>
  </thead>
  {% endif %}
  <tbody>
  {% for object in objects|sort_items_furnitures %}
  <tr>
    <th scope="col">
      {% if from_room is not None %}

      {% if object.box is not None %}
      <a href="{% url 'movingbox:get_room_box_item' from_room object.box.box_number object.id %}">
        {{ object.name }}
      </a>
      {% else %}
      <a href="{% url 'movingbox:get_room_furniture' from_room object.id %}">{{ object.name }}</a>
      {% endif %}

      {% else %}

      {% if object.box is not None %}
      <a href="{% url 'movingbox:get_item' object.id %}">{{ object.name }}</a>
      {% else %}
      <a href="{% url 'movingbox:get_furniture' object.id %}">{{ object.name }}</a>
      {% endif %}

      {% endif %}
    </th>
    {% if display_room %}
    <td scope="col">
      {% if object.box is not None %}
      <a href="{% url 'movingbox:get_room' object.box.room.id %}">{{ object.box.room.room_name }}</a>
      {% else %}
      <a href="{% url 'movingbox:get_room' object.room.id %}">{{ object.room.room_name }}</a>
      {% endif %}
    </td>
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
  {% if is_paginated and paginator_page.paginator.per_page < paginator_page.paginator.count %}
  <tfoot>
  <tr>
    <td colspan="2" class="justify-content-center w-100 text-center p-1 m-0">
      {% include 'object_paginator.html' %}
    </td>
  </tr>
  </tfoot>
  {% endif %}
</table>

movingbox/templates/search_items_form.html
{% load fontawesome %}
<form class="form-inline {{ form_class }}" action="{% url 'movingbox:post_search_items' %}"
      method="post" id="{{ input_id }}-form">
  {% csrf_token %}
  <input class="form-control {{ input_class }}" type="search" placeholder="Search Item/Furniture"
         aria-label="Search Item/Furniture" name="item_name" id="{{ input_id }}" value="{{ item_name }}"
         minlength="1">
  <button class="btn btn-primary {{ button_class }}" type="submit">{% fontawesome_icon 'search' %} Search</button>
</form>
<script>
$(document).ready(() => {
    $('#{{ input_id }}-form').on('submit', () => {
        let input_val = $('#{{ input_id }}').val();
        return !!(input_val);
    });
});
</script>